import turtle
win = turtle.Screen()

outline = turtle.Turtle()
outline.getscreen().title("NEPAL FLAG")
outline.pensize(10)
outline.color("blue")
outline.penup()
outline.backward(200)
outline.goto(-200, -200)
outline.pendown()
outline.goto(-200, 250)

outline.begin_fill()
outline.fillcolor("red")
outline.right(30)
outline.forward(400)
outline.setheading(180)
outline.forward(250)
outline.setheading(0)
outline.right(30)
outline.forward(400)
outline.setheading(180)
outline.forward(442.820323027551)
outline.setheading(0)
outline.end_fill()
outline.goto(-200, 250)

outline.pensize(2)
outline.color("black")
outline.penup()
outline.right(80)
outline.forward(130)
outline.right(-20)
outline.pendown()
outline.begin_fill()
outline.fillcolor("white")
outline.circle(80, 130)
outline.setheading(180)
outline.left(60)
outline.circle(-45, 60)
outline.setheading(90)
outline.right(75)
for i in range(8):
	outline.forward(12)
	outline.left(160)
	outline.forward(20)
	outline.right(150)
outline.setheading(180)
outline.circle(-45, 60)
outline.end_fill()

outline.color("black")
outline.penup()
outline.goto(-200, -150)
outline.setheading(0)
outline.left(30)
outline.forward(130)
outline.setheading(0)
outline.pendown()
outline.begin_fill()
outline.fillcolor("white")
for i in range(18):
	outline.right(60)
	outline.forward(30)
	outline.left(160)
	outline.forward(30)
	outline.right(80)
outline.end_fill()
outline.hideturtle()

turtle.done()